version: "3.8"

services:
  app:
    build: .
    working_dir: /app
    ports:
      - "9100:9001"
    configs:
      - source: envfile
        target: /app/.env
    command: uvicorn app:app --host 0.0.0.0 --port 9001

configs:
  envfile:
    file: ./gateway-notion.env

networks:
  default:
    driver: overlay
    attachable: true


