services:
  app:
    image: python:3.11
    working_dir: /app
    volumes:
      - ./:/app
      - ./gateway-notion.env:/app/.env
    command: ["sleep", "3600"]
    ports:
      - "9100:9001"
    networks:
      - portainer

