version: "3.8"

services:
  app:
    build: .
    ports:
      - "9100:9001"
    configs:
      - source: envfile
        target: /app/.env

configs:
  envfile:
    file: ./gateway-notion.env

networks:
  default:
    driver: overlay
    attachable: true


