services:
  - type: web
    name: gateway-notion
    env: python
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    preDeployCommand: |
      python -m prisma generate --schema=prisma/schema.prisma
      python migrate.py
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /docs
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
