services:
  - type: web
    name: gateway-notion
    env: python
    plan: free
    region: oregon
    autoDeploy: true

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m prisma --version
      python -m prisma generate --schema=prisma/schema.prisma

    startCommand: bash -lc "python -m prisma migrate deploy && uvicorn app:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /docs

    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      # As demais variáveis (JWT_SECRET, DATABASE_URL etc.) você configura no dashboard do Render
